name: python

on:
  schedule:
    - cron: "00 01 * * 1-5"
  pull_request:
    paths:
      - .github/workflows/python.yaml
      - 'images/python/*.yaml'
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/python.yaml
      - 'images/python/*.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  security-events: write
  actions: read

jobs:
  publish:
    strategy:
      matrix:
        version: ["3.12"]
        variant: [prod, shell, dev]
        # include:
        #   - version: "3.12"
        #     packages: 'python-3.12'
    name: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
    uses: './.github/workflows/release.yaml'
    with:
      tag: ${{ matrix.version }}${{ matrix.variant == 'shell' && '-shell' || matrix.variant == 'dev' && '-dev' || '' }}
      target: ${{ matrix.variant }}
      # packages: ${{ matrix.packages }}
      config-dir: images/python/${{ matrix.version }}
    secrets: inherit